# This is a basic workflow to help you get started with Actions

name: CI2

# Controls when the action will run.
on:
  workflow_dispatch:
    inputs:
      begin:
        description: 'begin'
        required: true
      end:
        description: 'end'
        required: true
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: |
          npm ci
          npm run start2
        env:
          begin: ${{ github.event.inputs.begin }}
          end: ${{ github.event.inputs.end }}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: pp
          path: ./pic/
